CREATE TABLE CUSTOMER (
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAME VARCHAR(50) NOT NULL,
STREET VARCHAR(20) NOT NULL,
CITY VARCHAR(20) NOT NULL,
STATE VARCHAR(20) NOT NULL,
ZIP VARCHAR(20) NOT NULL,
CREDIT_CARD_NUMBER VARCHAR(20) NOT NULL);

CREATE TABLE RENTAL (
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAME VARCHAR(50) NOT NULL,
RENTAL_TYPE VARCHAR(20) NOT NULL,
ENUM_TYPE VARCHAR(20) NOT NULL,
RATE FLOAT NOT NULL,
DAYS INTEGER NOT NULL);

INSERT INTO CUSTOMER (NAME, STREET, CITY, STATE, ZIP, CREDIT_CARD_NUMBER) VALUES('Anirban Das', 'Bangur Avenue', 'Kolkata', 'West Bengal', '700055', '4341-9987-6512-6542');
INSERT INTO CUSTOMER (NAME, STREET, CITY, STATE, ZIP, CREDIT_CARD_NUMBER) VALUES('Siddhartha Sengupta', 'Kuthar Junction', 'Mangalore', 'Karnataka', '575001', '6529-0087-1252-3097');
INSERT INTO CUSTOMER (NAME, STREET, CITY, STATE, ZIP, CREDIT_CARD_NUMBER) VALUES('Satanik Ganguly', 'Gachibowli', 'Hyderabad', 'Telangana', '500004', '5875-1200-9443-5681');
INSERT INTO CUSTOMER (NAME, STREET, CITY, STATE, ZIP, CREDIT_CARD_NUMBER) VALUES('Rohit Sarkar', 'Bhumkar Chowk', 'Pune', 'Maharashtra', '400012', '6345-0098-7612-3356');

INSERT INTO RENTAL (NAME, RENTAL_TYPE, ENUM_TYPE, RATE, DAYS) VALUES ('Anirban Das', 'SUV', 'Partial', 20.5, 10);
INSERT INTO RENTAL (NAME, RENTAL_TYPE, ENUM_TYPE, RATE, DAYS) VALUES ('Siddhartha Sengupta', 'SUV', 'Up Front', 20.5, 5);
INSERT INTO RENTAL (NAME, RENTAL_TYPE, ENUM_TYPE, RATE, DAYS) VALUES ('Satanik Ganguly', 'Hatchback', 'Partial', 5.0, 8);
INSERT INTO RENTAL (NAME, RENTAL_TYPE, ENUM_TYPE, RATE, DAYS) VALUES ('Rohit Sarkar', 'Sedan', 'Up Front', 13.87, 20);

SELECT * FROM CUSTOMER;

SELECT * FROM RENTAL;

DROP TABLE CUSTOMER;